version: '3.1'

volumes:
  portainer_data:

services:
  portainer:
    image: portainer/portainer-ce:2.18.4
    ports:
      - 8000:8000
      - 9000:9000
      - 9443:9443
    volumes:
      - portainer_data:/data
      # Local Environment
      - /var/run/docker.sock:/var/run/docker.sock
