version: '3.1'

volumes:
  db:

services:
  postgres:
    image: postgres:alpine3.16
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres123456
    volumes:
      - db:/var/lib/postgresql/data
