version: '3.1'

volumes:
  db:

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: RabbitMQUser
      RABBITMQ_DEFAULT_PASS: Rabbit123456
    volumes:
      - db:/var/lib/rabbitmq
