version: '3.1'

volumes:
  redis_data:

services:
  redis:
    image: redis:7.2.0
    command: redis-server --save 60 1 --loglevel warning --requirepass Redis123456
    ports:
      - 6379:6379 
    volumes:
      - redis_data:/data
